### ISSUE TITLE
zip with password

### ISSUE THREAD

**Issue by mkbsugita** [perron2/async-zip#4]
Does is support zip with password?

**Comment by claudiofelber** [comment]
No it does not. The C library this package is based on (https://github.com/kuba--/zip) does not support passwords and encryption either. So I would need to find another library and completely rewrite this package. This is currently not going to happen, sorry.

**Comment by mkbsugita** [comment]
It is C library.
Finally. I used this.

https://github.com/YuKiO-output/flutter_zip_archive
forked from https://github.com/jlcool/flutter_zip_archive
